name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Clear npm cache
      run: npm cache clean --force
      working-directory: frontend

    - name: Install Dependencies
      run: npm install
      working-directory: frontend

    - name: List installed packages
      run: npm list
      working-directory: frontend

    - name: Print working directory
      run: pwd
      working-directory: frontend

    - name: Build
      run: CI=false npm run build
      working-directory: frontend
